name: Deploy Svelte with Bun to GitHub Pages

on:
  push:
    branches:
      - main # หรือ branch ที่คุณใช้

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # ให้สิทธิ์ push ไป gh-pages

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
