name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # หรือเปลี่ยนเป็น branch ที่คุณใช้งาน

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write # สำคัญมาก! ต้องใช้สำหรับ push ไป gh-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # หรือเวอร์ชันที่คุณใช้
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
